[book]
authors = ["anxingan"]
language = "zh"
src = "src"
title = "mdbook-docs"

[output.html]
smart-punctuation = true
mathjax-support = true
hash-files = true

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelinesF]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
